# Define node version
FROM node:12.16.1-alpine
# Define container directory
WORKDIR /tariff-comparison-app-node
# Copy package*.json for npm install
COPY package*.json ./
# Run npm clean install, prod dependencies only
RUN npm ci --only=production
# Copy all files
COPY . .
# Expose port 3000 for server
EXPOSE 3000
# Run "node server/run.js"
CMD ["node", "server.js"]